### ISSUE TITLE
 get_register_name(&self, location: VarNode) Should not consume VarNode

### ISSUE THREAD

**Issue by chf0x** [toolCHAINZ/jingle#11]
Hi! I believe that get_register_name should obtain the location by reference instead of consuming the varnode. Or probably I am missing something? https://github.com/toolCHAINZ/jingle/blob/main/jingle/src/translator.rs#L68

**Comment by toolCHAINZ** [comment]
Ahh that is probably a leftover from back when I had `Varnode` impl `Copy`. I removed that for some reason, so yeah, it would be a little more ergonomic to avoid a clone here. I'll change this when I get a chance.

**Comment by toolCHAINZ** [comment]
Fixed in 262d530
