### ISSUE TITLE
Consider Moving LoadImage logic to Rust side of FFI boundary

### ISSUE THREAD

**Issue by toolCHAINZ** [toolCHAINZ/jingle#15]
Right now:

Image is made in Rust as a shared type, copied over to C++ and used to construct a `LoadImage`.

Could instead split it up a little differently:

```rust
/// impl this trait for those different types
trait ImageProvider{
  /// a rust version of LoadImage::load
  fn load(&self, offset: &VarNode, output: &mut [u8]) -> usize;
}

/// this is sent across the FFI
struct ImageFFI<'a>{
  img: Box<dyn ImageProvider + 'a>;
}

impl<'a> ImageProvider for ImageFFI<'a>{
   fn load(&self, offset: &VarNode, output: &mut [u8]) -> usize{
     self.img.load(offset, output)
   }
}
```

Now, the `ImageFFI` can be sent across the FFI boundary as an opaque type and `ImageFFI::load` can be exposed as an `extern "Rust"` function.

The `LoadImage` can then just give the opaque `ImageFFI` handle to `ImageFFI::load`. I think this also allows `ImageFFI` to work with owned data and elide its lifetime in many cases.

**Comment by chf0x** [comment]
Oh wow, so fast. Mate you are amazing!
