### ISSUE TITLE
wrong PcodeOperation::Load display() ?

### ISSUE THREAD

**Issue by chf0x** [toolCHAINZ/jingle#21]
Hi, the current `PcodeOperation::Load` display output appears as follows:
```
RIP = LOAD *(ram[RSP]:8), RSP
```
Probably it should instead be:
```
RIP = LOAD *(ram[RSP]:8)
```

**Comment by toolCHAINZ** [comment]
Oops, looks like a copy paste error, good catch, I'll fix that
